spring:
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    flyway:
        enabled: true
        baseline-on-migrate: false

logging:
    level:
        root: warn
        '[io.github.projetorotina]': info